plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}
/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "tc-discord-webhooks"
include(":tc-discord-webhooks-server")
include(":build")
