/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
    kotlin("jvm") version "2.3.0"
}

dependencies {
    testImplementation(libs.org.jetbrains.teamcity.tests.support)
    compileOnly(libs.org.jetbrains.teamcity.server.api)
    compileOnly(libs.org.jetbrains.teamcity.server.web.api)
    implementation(kotlin("stdlib"))
}

description = "tc-discord-webhooks-server"

java {
    withJavadocJar()
}
repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(24)
}