/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://download.jetbrains.com/teamcity-repository")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    testImplementation("org.testng:testng:6.8.21")
    testImplementation("com.github.tomakehurst:wiremock-jre8:2.23.2")
    compileOnly("org.apache.httpcomponents:httpclient:4.5.6")
    compileOnly("com.google.code.gson:gson:2.4")
}

group = "com.github.playerforcehd"
version = "1.1.2"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

tasks.named<Test>("test") {
    useTestNG()
}
